services:
  - type: web
    name: ghostfrog-site
    env: python
    plan: free
    rootDirectory: ghostfrog-python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
    healthCheckPath: /
